### ISSUE TITLE
To-dos

### ISSUE THREAD

**Issue by theJasonFan** [COMBINE-lab/mazu#1]
# To-dos:

## Must
- [ ] Basic usage / lib documentation (use `rustdoc`)
- [ ] Stabilize upstream dependencies, i.e., merge thejasonfan form of kme.rs back to combine-lab
- [ ] fix or remove `num_bits` (size on heap) measurements
- [ ] Note new canonical minimimizer definition

## Nice-to-haves
- [ ] `pufferfish2` sparse unitig table sampling
- [ ] RefSeqCollection with PolyNs.  We can build from FASTA files but we can't 2-bit encode and represent RefSeqs with PolyN stretches right now.
- [ ] Officially supported modular serialization so constituent index components are easy to measure. But for now, we can let CLIs that use `mazu` handle provenance and serialization formats.

## New algorithms / features
- [ ] Standardized index info as JSON/YAML for supported "default / official" indexes.
- [ ] Generic (or more boilerplate) for K2U implementations to cache and to skip rank/select queries (to retrieve unitig length and start position) for consecutive k-mers mapping to the same unitig.

## Extras:
- [ ] Pufferfish (C++) to mazu conversion for Sparse and Dense indexes.
- [ ] #2
- [ ] Basic benchmarks for some atomic data structures EF, rank/sel, WM etc.
- [ ] #5

## Benchmarking / Questions:
- [ ] Compare mazu PolyN handling vs. pufferfish's pseudorandom insertion for Ns
- [ ] Note and benchmark differences to SSHash (canonical minimizer parsing + a more naive skew index)
